OnlineExamPortalProject/Controllers/AllTestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OnlineTest.Models;

namespace OnlineTest.Controllers
{
 


    public class AllTestController : Controller


    {
        //This controller Will handle all test Code Here
        // GET: AllTest
        private OnlineTestDBEntities db = new OnlineTestDBEntities();
        public static int result = 0;
        public ActionResult PythonTest()   //Python Test
        {

            string test = "Python";
            var questions = db.Questions.Where(s => s.Test_Name == test).ToList();

            return View(questions);

        }
        public ActionResult CSharpTest()   //C# Test
        {
            string test = "C#";
            var questions = db.Questions.Where(s => s.Test_Name == test).ToList();

            return View(questions);

        }
        public ActionResult JAVATest()  //Java Test
        {
            string test = "JAVA";
            var questions = db.Questions.Where(s => s.Test_Name == test).ToList();

            return View(questions);

        }
        public ActionResult ADOTest()  //ADO.Net test
        {
            string test = "ADO";
            var questions = db.Questions.Where(s => s.Test_Name == test).ToList();

            return View(questions);

        }

        public ActionResult PythonInstruction()
        {
            return View();

        }

        public ActionResult CSharpInstruction()
        {
            return View();
        }

        public ActionResult JAVAInstruction()
        {
            return View();
        }

        public ActionResult ADOInstruction()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CheckAnswerPython(string Answer, String Question_Answer)
        {
            //string correctanswer = TempData["CorrectAnswer"].ToString();
            if (Answer == Question_Answer)
            {
                result = result + 5;
            }
             
            ViewBag.Result = result;
            return RedirectToAction("PythonTest");

        }

        [HttpPost]
        public ActionResult CheckAnswerCSharp(string Answer, String Question_Answer)
        {
            //string correctanswer = TempData["CorrectAnswer"].ToString();
            if (Answer == Question_Answer)
            {
                result = result + 5;
            }
 
            ViewBag.Result = result;
            return RedirectToAction("CSharpTest");

        }

        [HttpPost]
        public ActionResult CheckAnswerJAVA(string Answer, String Question_Answer)
        {
            //string correctanswer = TempData["CorrectAnswer"].ToString();
            if (Answer == Question_Answer)
            {
                result = result + 5;
            }
 
            ViewBag.Result = result;
            return RedirectToAction("JAVATest");

        }


        [HttpPost]
        public ActionResult CheckAnswerADO(string Answer, String Question_Answer)
        {
            //string correctanswer = TempData["CorrectAnswer"].ToString();
            if (Answer == Question_Answer)
            {
                result = result + 5;
            }
 
            ViewBag.Result = result;
            return RedirectToAction("ADOTest");

        }


        public ActionResult Result()
        {
            ViewBag.Finalresult = result;
            return View();
        }

    }
    }

OnlineExamPortalProject/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OnlineTest.Models;

namespace OnlineTest.Controllers
{
    public class HomeController : Controller
    {
        private OnlineTestDBEntities db = new OnlineTestDBEntities(); //instance creation

        //**************************************** Index ************************************

        public ActionResult Index()
        {
            return View();
        }

        //**************************************** User Registration ****************************

        public ActionResult Register()   //Registration Of new User to the Website
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Register(UserTable usr)
        {
            if (ModelState.IsValid)
            {
                db.UserTables.Add(usr); //Adding User
                db.SaveChanges(); //Saving Changes
                ViewBag.SuccessMessage = "Registration Succesful"; //Displaying Message after Registration
            }
            return RedirectToAction("Login");
        }

        //****************************************  User Login ***************************************

        public ActionResult Login()    //Login For user for Entering in Website for Test
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(UserTable usr)
        {
            if (ModelState.IsValid)
            {
                //****Login logic*****

                var details = (from userlist in db.UserTables
                               where userlist.User_Name == usr.User_Name && userlist.User_Password == usr.User_Password
                               select new
                               {
                                   userlist.User_Id,
                                   userlist.User_Name
                               }).ToList();
                if (details.FirstOrDefault() != null)
                {
                    Session["User_Id"] = details.FirstOrDefault().User_Id;
                    Session["User_Name"] = details.FirstOrDefault().User_Name;
                    return RedirectToAction("Courses"); //if login successful, then redirect to Courses Page
                }
                else
                {
                    ViewBag.message = "Invalid Credentials"; //Error Message
                }
            }
            return View(usr);
        }

        //**************************************** Welcome **************************************
        public ActionResult Welcome()
        {
            return View();
        }

        //**************************************** Courses **************************************
        public ActionResult Courses()   //It will Display all courses Available in the Database
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Courses(UserTable usr)
        {
            return RedirectToAction("Instructions"); //Redirecting to Instructions Page
        }

        //**************************************** User Instructions **************************************
        public ActionResult Instructions()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Instructions(Question qustn)
        {
            return RedirectToAction("CSharp", "Question");
        }

        //**************************************** About Page **************************************
        public ActionResult About()
        {
            ViewBag.Message = "ABOUT US.";

            return View();
        }

        //**************************************** Contact Page**************************************
        public ActionResult Contact()
        {
            ViewBag.Message = "CONTACT US.";

            return View();
        }
    }
}

OnlineExamPortalProject/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
    Layout = "View.cshtml";
}

<h3>@ViewBag.Message</h3>

<p>
    Online Exam Portal

    Online Examination System is a technology-driven way to simplify examination activities like defining exam patterns with question banks, defining exam timer, objective/ subjective question sections, conducting exams using the computer or mobile devices in a paperless manner.

    Online Examination System is a cost-effective, scalable way to convert traditional pen and paper-based exams to online and paperless mode.

    Candidates can appear for the exam using any desktop, laptop, or mobile device with a browser. Exam results can be generated instantly for the objective type of questions.

    We at Spayee, are help educators reach out to masses with affordable and scalable technology.

    We offer a white-labeled course distribution platform to create, market & sell your online courses and digital products.  From solo edupreneurs to massive educational institutes, our platform is used by top educators, youtubers & influencers.

    If you are looking for a comprehensive course platform where you can launch and nurture your online courses, Spayee would be the one for you.

    Build your online course platform within minutes.

    Sign up now!

</p>

OnlineExamPortalProject/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
    Layout = "View.cshtml";
}

<h3>@ViewBag.Message</h3>

<address>
    Online Test Management Company<br />
    Chennai, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

OnlineExamPortalProject/Views/Home/Courses.cshtml


@{
    ViewBag.Title = "TestSelection";
    Layout = "View.cshtml";
}
<link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
<link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
<script src="~/Scripts/modernizr-2.6.2.js"></script>
<html>
<body>
    <div class="container-sm" style="margin:auto;width:500px;text-align:center">
        <h2>Choose Test</h2>
        <br />
        @*<input type="submit" onclick="location.href='@Url.Action("Index","AllTest")'" />*@
        <button id="btn1" type="button" class="btn btn-primary" onclick="location.href='@Url.Action("PythonInstruction","AllTest")'">Python</button><br /><br />
        <button id="btn2" type="button" class="btn btn-primary" onclick="location.href='@Url.Action("CSharpInstruction","AllTest")'">C#</button><br /><br />
        <button id="btn3" type="button" class="btn btn-primary" onclick="location.href='@Url.Action("JAVATest","AllTest")'">JAVA</button><br /><br />
        <button id="btn4" type="button" class="btn btn-primary" onclick="location.href='@Url.Action("ADOTest","AllTest")'">ADO.Net</button>

    </div>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>





OnlineExamPortalProject/Views/Home/Index.cshtml

@{
    ViewBag.Title = "Index";
    Layout = "View1.cshtml";
}

 <h2><b>Welcome To Online Exam Portal</b></h2>
<img src="~/Image/student-passing-online-exam-home-closeup-178208932.jpg" width="100%"  />
<p>
Every organization is different. That's why we've created affordable Online Testing Plans to suit all requirements.
From occasional usage to Enterprise Quiz Maker requirements,ClassMarker is your Secure & reliable exam maker & online testing solution

   </p>

OnlineExamPortalProject/Views/Home/Instructions.cshtml

@model OnlineTest.Models.UserTable

@{
    ViewBag.Title = "Instructions";
    Layout = "View.cshtml";
}

<h2>Instructions</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />

        <div class="form-group">

            <div class="col-md-10">
                <ol>
                    <li>This Online Test Consists of 10 Questions. Each question carries 1 Mark.</li>
                    <li>Your session is recorded. Nagivating to any other tabs is considered as Malpractice.</li>
                    <li>Click "Begin Test" to take the exam.</li>
                </ol>


            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Begin Test" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Courses")
</div>


OnlineExamPortalProject/Views/Home/Login.cshtml

@model OnlineTest.Models.UserTable

@{
    ViewBag.Title = "Login";
    Layout = "View.cshtml";
}
@if (ViewBag.message != null)
{
    <div class="alert alert-danger">
        <strong>Error!</strong> @ViewBag.message
    </div>

}





@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h2 >Login</h2>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.User_Name, "UserName", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.User_Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.User_Name, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            @Html.LabelFor(model => model.User_Password, "Password", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.PasswordFor(model => model.User_Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.User_Password, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Login" class="btn btn-default" />
            </div>
        </div>
    </div>
}

 

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>


OnlineExamPortalProject/Views/Home/Register.cshtml
@model OnlineTest.Models.UserTable

@{
    ViewBag.Title = "Register";
    Layout = "View.cshtml";

}

<h2>Register</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>UserTable</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.User_Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.User_Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.User_Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.User_Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.User_Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.User_Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.User_Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.User_Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.User_Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Gender, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Contact_Number, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Contact_Number, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Contact_Number, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

OnlineExamPortalProject/Views/Home/View.cshtml


<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>

<body style="color:black; background-color:burlywood;background-image:url('../../Image/backgroud Image.jpg');background-repeat:no-repeat">

    <div class="navbar navbar-inverse navbar-fixed-top">
        <h1 style="color:burlywood;text-align:center"><b><i>Online Exam Portal</i></b></h1>

        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @*@Html.ActionLink("Online Test Management", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@
            </div>
            <div class="navbar-collapse collapse">
                <h3>
                    <ul class="nav navbar-nav">

                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("About", "About", "Home")</li>
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                        <li>@Html.ActionLink("Register", "Register", "Home")</li>
                        <li>@Html.ActionLink("UserLogin", "Login", "Home")</li>
                        <li>@Html.ActionLink("Admin", "login", "Account")</li>

                    </ul>
                </h3>
            </div>
        </div>
    </div>
    <br />
    <br />
    <br />
    <br />
    <br />
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Online Exam Portal</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>



OnlineExamPortalProject/Views/Home/View1.cshtml


<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>

<body style="color:black; background-color:burlywood;">

    <div class="navbar navbar-inverse navbar-fixed-top">
        <h1 style="color:burlywood;text-align:center"><b><i>Online Exam Portal</i></b></h1>

        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @*@Html.ActionLink("Online Test Management", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@
            </div>
            <div class="navbar-collapse collapse">
                <h3>
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("About", "About", "Home")</li>
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                        <li>@Html.ActionLink("Register", "Register", "Home")</li>
                        <li>@Html.ActionLink("UserLogin", "Login", "Home")</li>
                        <li>@Html.ActionLink("Admin", "login", "Account")</li>

                    </ul>
                </h3>
            </div>
        </div>
    </div>
    <br />
    <br />
    <br />
    <br />
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Online Exam Portal</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

